import type { ParsedStatement } from "../../parser/types";
import type { CheckContext, Rule } from "./types";

const SERIAL_TYPES = ["serial", "bigserial", "smallserial"];

const detect = (statement: ParsedStatement, _context: CheckContext): boolean => {
  return (
    statement.type === "alterTable" &&
    statement.action === "addColumn" &&
    SERIAL_TYPES.includes(statement.dataType?.toLowerCase() ?? "")
  );
};

const message = (statement: ParsedStatement): string => {
  return `Adding column "${statement.column}" with serial type locks the table`;
};

const suggestion = (_statement: ParsedStatement): string => {
  return `
❌ Bad: Adding a column with serial type creates a sequence and rewrites the table with default values

✅ Good: Use identity columns instead:
   ALTER TABLE "table_name" ADD COLUMN "column_name"
     integer GENERATED BY DEFAULT AS IDENTITY;

   Or add a sequence separately to avoid table rewrite:
   1. Create a sequence: CREATE SEQUENCE "seq_name";
   2. Add column without default: ALTER TABLE "table_name" ADD COLUMN "column_name" integer;
   3. Set default: ALTER TABLE "table_name" ALTER COLUMN "column_name"
        SET DEFAULT nextval('"seq_name"');

To skip this check, add above the statement:
   -- prisma-strong-migrations-disable-next-line addAutoIncrement
`.trim();
};

export const addAutoIncrementRule: Rule = {
  name: "addAutoIncrement",
  severity: "error",
  description: "Adding a column with serial type locks the table",
  detect,
  message,
  suggestion,
};
