import type { Rule } from "../types";

export const addAutoIncrementRule: Rule = {
  name: "add_auto_increment",
  code: "SM014",
  severity: "error",
  description: "Adding a column with serial type locks the table",

  detect: (stmt) =>
    stmt.type === "alterTable" &&
    stmt.action === "addColumn" &&
    ["serial", "bigserial", "smallserial"].includes(stmt.dataType?.toLowerCase() ?? ""),

  message: (stmt) => `Adding column "${stmt.column}" with serial type locks the table`,

  suggestion: (_stmt) =>
    `
❌ Bad: Adding a column with serial type creates a sequence and rewrites the table with default values

✅ Good: Use identity columns instead:
   ALTER TABLE "table_name" ADD COLUMN "column_name"
     integer GENERATED BY DEFAULT AS IDENTITY;

   Or add a sequence separately to avoid table rewrite:
   1. Create a sequence: CREATE SEQUENCE "seq_name";
   2. Add column without default: ALTER TABLE "table_name" ADD COLUMN "column_name" integer;
   3. Set default: ALTER TABLE "table_name" ALTER COLUMN "column_name"
        SET DEFAULT nextval('"seq_name"');

To skip this check, add above the statement:
   -- prisma-strong-migrations-disable-next-line add_auto_increment
`.trim(),
};
